version: '3'

services:
  go_app:
    container_name: go_app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "root:j1751502021@tcp(database:3306)/notesAPI_II?charset=utf8&parseTime=True&loc=Local"
    ports:
      - "8080:8080"
    depends_on:
      - database
  database:
    container_name: database
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: j1751502021
      MYSQL_DATABASE: notesAPI_II
      MYSQL_USER: davi
      MYSQL_PASSWORD: j1751502021
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: {}
